spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: video-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
server:
  port: 8082
  tomcat:
    # 5분 (300,000ms)
    connection-timeout: 300000
    keep-alive-timeout: 300000

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
#AWS Configuration
aws:
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket-name: "${AWS_BUCKET_NAME}"
